vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        deal_image_file:
            uri_prefix: /images/deals
            upload_destination: '%kernel.project_dir%/public/images/deals'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_remove: true
        promo_code_image_file:
            uri_prefix: /images/promoCodes
            upload_destination: '%kernel.project_dir%/public/images/promoCodes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_remove: true